---
title: "NGupta_HW3"
author: "Nikhil Gupta"
date: "September 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Problem 1
####Commands to clone awesome-public-datasets Github repo <br />?

mkdir Week3 <br /> 
cd Week3/ <br /> 
git clone https://github.com/awesomedata/awesome-public-datasets.git <br /> 


```{r Problem 2}

## 2A ##
df <- read.csv("awesome-public-datasets/Datasets/titanic.csv/titanic.csv") # read file from relative path 

# Exploratory Data Analysis
str(df)
head(df)

## 2B ##
# Breakdown by Sex
sex <- table(df$Sex)
print ("Breakdown by Sex:")
print (sex)
barplot(sex, main = "Breakdown by Sex", xlab = "Sex", ylab = "Count") ## need to add titles, etc

## 2C
# Check for misssing values
anyNA(df$Age)
anyNA(df$Fare)
anyNA(df$Survival)

sapply(df[,c('Age','Fare','Survived')], mean, na.rm=TRUE) # Find the means removing any NA values

```

```{r Problem 3}
sleep <- read.csv("HW3/sleep_data_01.csv")
str(sleep) #EDA to get variable names

helper <-  function(data){
  ## 3A
  median.age <- median(data$Age, na.rm = TRUE)
  min.sleep <- min(data$Duration , na.rm = TRUE)
  max.sleep <- max(data$Duration, na.rm = TRUE)
  mean.RSES <- mean(data$RSES, na.rm = TRUE)
  sd.RSES <- sd(sleep$RSES, na.rm = TRUE)
  
  range.sleep <- max.sleep - min.sleep
  
  ## 3B
  report <- data.frame (median.age,mean.RSES,sd.RSES,range.sleep)
  
  ## 3C
  colnames(report) <- c("MedianAge","SelfEsteem","SE_SD","DurationRange")
  
  ## 3D
  round(report,2)
}

## 3E
helper(sleep)

```


```{r Problem 4}

# 4A
#install.packages("fivethirtyeight") # uncomment if not already installed; you can leave it commented if you have already installed it
library(fivethirtyeight)

#4B
# To see a list of all data sets:
alldata <- data(package = "fivethirtyeight")

# Explore what data gets returned 
str(alldata)
alldata$results[22,] # Chrck out the 22nd item

data("college_recent_grads", package = 'fivethirtyeight') # Download 22nd dataset
df <- college_recent_grads # reassign to dataframe called 'df'

# 4C
vignette("fivethirtyeight", package = "fivethirtyeight") # To see more detailed list of the dataset
# News Story URL: https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/

# 4D
dim(df) # Dimensions of dataframe
colnames(df) # Column names of dataframe


```

```{r Problem 5}
# 5A
# Columns names have already been mentioned above so not repeating again.
length(colnames(df)) # Count the nuber of columns

# 5B
major_count <- table(df$major_category)
major_count
 
# 5C
par(las=2)
?college_recent_grads # Getmore detail on dataset
# Plot barplot; Column Labels dont need to be added since they will be picked from the column names by default.
barplot(major_count, horiz = TRUE, col = rainbow(20)
        ,main = 'Count of Majors in each Catrgory'
        ,xlab = 'Count'
        ,ylab = "Category of major from Carnevale et al"
        )


# 5D 
write.csv(df,file = "CollegeMajors.csv", row.names = FALSE) # writes to directory in which Rmd is stored

```

### Problem 6
#### Github Repo: https://github.com/ngupta23/SMU-MSDS6306.git 


